name: user
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # major
  timeago: ^3.0.2
  cached_network_image: ^3.0.0
  flutter_bloc: ^7.0.0
  get_it: ^7.1.3
  #  helpers
  injectable: ^1.0.5
  json_annotation: ^4.0.1
  rxdart: ^0.27.0
  freezed_annotation: ^0.14.2
  dartz: ^0.9.2
  package_info: ^0.4.0+16
  geocoder: ^0.2.1
  location: ^4.3.0
  fluttertoast: ^8.0.6
  flushbar: ^1.10.4
  # firebase
  firebase_storage: ^8.0.6
  firebase_dynamic_links: ^4.0.3
  firebase_database: ^6.1.2
  cloud_firestore: ^2.1.0
  firebase_messaging: ^10.0.7
  google_sign_in: ^5.2.1
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4 # packages
  linkedin_login: ^2.0.1
  dio: ^4.0.4
  qr_flutter: ^4.0.0
  share: ^2.0.4
  country_code_picker: ^2.0.2
  qr_code_scanner: ^0.6.1
  core:
    path: ../core
  college:
    path: ../college
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.3
  freezed: ^0.14.2
  injectable_generator: ^1.4.0
  json_serializable: ^4.1.2

flutter:
