name: core
description: A new Flutter package project.
version: 0.0.1
homepage: null
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  flushbar: ^1.10.4
  intl: null
  url_launcher: ^6.0.3
  cloud_firestore: ^2.1.0
  flutter_bloc: ^7.0.0
  firebase_auth: ^1.1.4
  firebase_storage: ^8.0.6
  geocoder: ^0.2.1
  location: ^4.3.0
  package_info: ^0.4.0+16
  pin_code_fields: ^7.1.0
  image_picker: ^0.7.5
  image_cropper: ^1.4.0
  lottie: ^1.2.1
  dartz: ^0.9.2
  get_it: ^7.1.3
  file_picker: ^4.3.3
  razorpay_flutter: ^1.2.7
  flutter_secure_storage: ^5.0.2
  cached_network_image: ^3.0.0
  country_code_picker: ^2.0.2
  webview_flutter: ^2.0.4
  freezed_annotation: ^0.14.2
  injectable: ^1.0.5
  dropdown_button2: ^1.0.7
  dio: ^4.0.4
  cashfree_pg: ^2.0.4+24
  firebase_dynamic_links: ^4.0.3
  user:
    path: ../user
  college:
    path: ../college
  canteen:
    path: ../canteen
  blogs:
    path: ../blogs
dev_dependencies:
  flutter_lints: ^1.0.0
  injectable_generator: ^1.4.0
  build_runner: ^2.0.3
  freezed: ^0.14.2
  json_serializable: ^4.1.2
  lint: ^1.5.3
  flutter_test:
    sdk: flutter

flutter:
