mixin LanguagesList {
  static List<String> getLanguagesList() {
    return [
      "Mandarin Chinese",
      "Spanish",
      "English",
      "Hindi ",
      "Bengali",
      "Portuguese",
      "Russian",
      "Japanese",
      "Punjabi",
      "Marathi",
      "Telugu",
      "Turkish",
      "Korean",
      "French",
      "German ",
      "Vietnamese",
      "Tamil",
      "Urdu ",
      "Javanese",
      "Italian",
      "Arabic",
      "Gujarati",
      "Persian",
      "Bhojpuri",
      "Min",
      "Hakka",
      "Hausa",
      "Kannada",
      "Indonesian",
      "Polish",
      "Yoruba",
      "Malayalam",
      "Odia",
      "Maithili",
      "Burmese",
      "Sunda",
      "Ukrainian",
      "Igbo",
      "Northern Uzbek",
      "Sindhi",
      "Romanian",
      "Tagalog",
      "Dutch",
      "Amharic",
      "Pashto",
      "Magahi",
      "Thai",
      "Saraiki",
      "Khmer",
      "Chhattisgarhi",
      "Somali",
      "Malaysian ",
      "Cebuano",
      "Nepali",
      "Assamese",
      "Sinhalese",
      "Northern Kurdish",
      "Nigerian Fulfulde",
      "Bavarian",
      "South Azerbaijani",
      "Greek",
      "Chittagonian",
      "Kazakh",
      "Deccan",
      "Hungarian",
      "Kinyarwanda",
      "Zulu",
      "Rundi",
      "Czech",
      "Uyghur",
      "Sylheti",
      "Sanskrit",
    ];
  }
}
